# !/bin/bash

# Datproc Image Version
export DATAPROC_IMAGE_VERSION='2.0-debian10'


# OPTIONAL. Leave empty if not required
export DATAPROC_OPTIONAL_COMPONENTS='JUPYTER,PRESTO'
export DATAPROC_SCALING_POLICY='demo-scaling-policy'
export DATAPROC_METASTORE='demo-metastore' 
export DATAPROC_INITIALISATION_SCRIPTS=''  # comma delimited list of scripts e.g. gs://'${GCS_BUCKET}'/dataproc/initialisation_actions/change_to_local_ssd.sh
export DATAPROC_PROPERTIES='dataproc:efm.spark.shuffle=primary-worker' # comma delimited list of scripts

export MASTER_MACHINE_TYPE='n2d-standard-2'
export MASTER_BOOT_DISK_GB=100
export MASTER_LOCAL_SSD_NUM=2

export WORKER_MACHINE_TYPE='n2d-standard-2'
export WORKER_BOOT_DISK=100
export WORKER_LOCAL_SSD_NUM=2
export WORKER_PRIMARY_CNT=2
export WORKER_SECONDARY_CNT=2

echo DATAPROC_OPTIONAL_COMPONENTS=$DATAPROC_OPTIONAL_COMPONENTS
echo DATAPROC_SCALING_POLICY=$DATAPROC_SCALING_POLICY
echo DATAPROC_METASTORE=$DATAPROC_METASTORE
echo DATAPROC_INITIALISATION_SCRIPTS=$DATAPROC_INITIALISATION_SCRIPTS
echo DATAPROC_PROPERTIES=$DATAPROC_PROPERTIES
echo MASTER_MACHINE_TYPE=$MASTER_MACHINE_TYPE
echo MASTER_BOOT_DISK_GB=$MASTER_BOOT_DISK_GB
echo MASTER_LOCAL_SSD_NUM=$MASTER_LOCAL_SSD_NUM
echo WORKER_MACHINE_TYPE=$WORKER_MACHINE_TYPE
echo WORKER_BOOT_DISK=$WORKER_BOOT_DISK
echo WORKER_LOCAL_SSD_NUM=$WORKER_LOCAL_SSD_NUM
echo WORKER_PRIMARY_CNT=$WORKER_PRIMARY_CNT
echo WORKER_SECONDARY_CNT=$WORKER_SECONDARY_CNT 